import { WorkCategory, WorkUnit } from '@/types';

export interface CatalogItem {
  id: string;
  category: WorkCategory;
  categoryNameSk: string;
  categoryNameRu: string;
  nameSk: string;
  nameRu: string;
  unit: WorkUnit;
  defaultCostLabor: number;    // Себестоимость работы мастера (€)
  defaultCostMaterial: number; // Примерная стоимость чернового материала (€)
  defaultClientPrice: number;  // Рекомендуемая цена клиенту (€)
  descriptionRu?: string;
}

export const CONSTRUCTION_CATALOG: CatalogItem[] = [
  // ДЕМОНТАЖ (Búracie a demontážne práce)
  {
    id: 'dem-01',
    category: 'demolition',
    categoryNameSk: 'Búracie práce',
    categoryNameRu: 'Демонтажные работы',
    nameSk: 'Búranie priečok (tehla/pórobetón do 15cm)',
    nameRu: 'Демонтаж перегородок (кирпич/газобетон до 15 см)',
    unit: 'm2',
    defaultCostLabor: 8,
    defaultCostMaterial: 0,
    defaultClientPrice: 15,
    descriptionRu: 'Снос ненесущих перегородок',
  },
  {
    id: 'dem-02',
    category: 'demolition',
    categoryNameSk: 'Búracie práce',
    categoryNameRu: 'Демонтажные работы',
    nameSk: 'Búranie železobetónových priečok',
    nameRu: 'Демонтаж железобетонных стен',
    unit: 'm2',
    defaultCostLabor: 25,
    defaultCostMaterial: 2,
    defaultClientPrice: 45,
    descriptionRu: 'Резка и алмазный демонтаж бетона',
  },
  {
    id: 'dem-03',
    category: 'demolition',
    categoryNameSk: 'Búracie práce',
    categoryNameRu: 'Демонтажные работы',
    nameSk: 'Osekávanie starých obkladov a dlažieb',
    nameRu: 'Сбивка старой плитки и кафеля',
    unit: 'm2',
    defaultCostLabor: 5,
    defaultCostMaterial: 0,
    defaultClientPrice: 9.5,
  },
  {
    id: 'dem-04',
    category: 'demolition',
    categoryNameSk: 'Búracie práce',
    categoryNameRu: 'Демонтажные работы',
    nameSk: 'Odstránenie starej podlahy (parkety, PVC, poter)',
    nameRu: 'Демонтаж старого пола (паркет, линолеум, стяжка)',
    unit: 'm2',
    defaultCostLabor: 4.5,
    defaultCostMaterial: 0,
    defaultClientPrice: 8,
  },
  {
    id: 'dem-05',
    category: 'demolition',
    categoryNameSk: 'Búracie práce',
    categoryNameRu: 'Демонтажные работы',
    nameSk: 'Vynesenie a odvoz sutiny (kontajner)',
    nameRu: 'Вынос мусора и вывоз контейнером',
    unit: 'kpl',
    defaultCostLabor: 180,
    defaultCostMaterial: 150,
    defaultClientPrice: 450,
  },

  // КЛАДКА И СТЯЖКА (Murárske a betonárske práce)
  {
    id: 'mas-01',
    category: 'masonry',
    categoryNameSk: 'Murárske práce',
    categoryNameRu: 'Кладочные и общестроительные работы',
    nameSk: 'Murovanie priečok Ytong / Porfix (10-15cm)',
    nameRu: 'Кладка перегородок Ytong / Porfix (10-15 см)',
    unit: 'm2',
    defaultCostLabor: 12,
    defaultCostMaterial: 9,
    defaultClientPrice: 28,
  },
  {
    id: 'mas-02',
    category: 'masonry',
    categoryNameSk: 'Murárske práce',
    categoryNameRu: 'Кладочные и общестроительные работы',
    nameSk: 'Cementový / anhydritový poter podlahy (do 5cm)',
    nameRu: 'Стяжка пола цементная / ангидридная (до 5 см)',
    unit: 'm2',
    defaultCostLabor: 7,
    defaultCostMaterial: 6,
    defaultClientPrice: 18,
  },
  {
    id: 'mas-03',
    category: 'masonry',
    categoryNameSk: 'Murárske práce',
    categoryNameRu: 'Кладочные и общестроительные работы',
    nameSk: 'Samonivelizačná stierka podlahy (do 5mm)',
    nameRu: 'Самонивелирующаяся стяжка (наливной пол)',
    unit: 'm2',
    defaultCostLabor: 4,
    defaultCostMaterial: 5,
    defaultClientPrice: 12.5,
  },
  {
    id: 'mas-04',
    category: 'masonry',
    categoryNameSk: 'Murárske práce',
    categoryNameRu: 'Кладочные и общестроительные работы',
    nameSk: 'Vnútorná vápenno-cementová / sadrová omietka',
    nameRu: 'Внутренняя штукатурка стен (гипсовая/цементная)',
    unit: 'm2',
    defaultCostLabor: 8,
    defaultCostMaterial: 4.5,
    defaultClientPrice: 16.5,
  },

  // ГИПСОКАРТОН (Sadrokartónové konštrukcie)
  {
    id: 'sdk-01',
    category: 'plasterboard',
    categoryNameSk: 'Sadrokartón',
    categoryNameRu: 'Гипсокартонные конструкции',
    nameSk: 'Montáž sadrokartónového stropu (rovný)',
    nameRu: 'Монтаж подвесного потолка из ГКЛ (ровный)',
    unit: 'm2',
    defaultCostLabor: 11,
    defaultCostMaterial: 9,
    defaultClientPrice: 26,
  },
  {
    id: 'sdk-02',
    category: 'plasterboard',
    categoryNameSk: 'Sadrokartón',
    categoryNameRu: 'Гипсокартонные конструкции',
    nameSk: 'Montáž sadrokartónovej priečky (dvojitý záklop + vata)',
    nameRu: 'Перегородка из ГКЛ (2 слоя + шумоизоляция)',
    unit: 'm2',
    defaultCostLabor: 14,
    defaultCostMaterial: 13,
    defaultClientPrice: 35,
  },
  {
    id: 'sdk-03',
    category: 'plasterboard',
    categoryNameSk: 'Sadrokartón',
    categoryNameRu: 'Гипсокартонные конструкции',
    nameSk: 'LED podhľad / svetelná rampa zo sadrokartónu',
    nameRu: 'Скрытый короб под LED-подсветку из ГКЛ',
    unit: 'bm',
    defaultCostLabor: 15,
    defaultCostMaterial: 8,
    defaultClientPrice: 32,
  },

  // ПЛИТКА И ПОЛЫ (Obklady, dlažby a podlahy)
  {
    id: 'fl-01',
    category: 'floors_tiles',
    categoryNameSk: 'Obklady a podlahy',
    categoryNameRu: 'Плитка и напольные покрытия',
    nameSk: 'Pokládka obkladu / dlažby štandard (do 60x60cm)',
    nameRu: 'Укладка плитки / керамогранита стандарт (до 60х60 см)',
    unit: 'm2',
    defaultCostLabor: 16,
    defaultCostMaterial: 6,
    defaultClientPrice: 30,
  },
  {
    id: 'fl-02',
    category: 'floors_tiles',
    categoryNameSk: 'Obklady a podlahy',
    categoryNameRu: 'Плитка и напольные покрытия',
    nameSk: 'Pokládka veľkoformátového obkladu (120x60cm a viac)',
    nameRu: 'Укладка крупноформатного керамогранита (120х60 см+)',
    unit: 'm2',
    defaultCostLabor: 25,
    defaultCostMaterial: 8,
    defaultClientPrice: 45,
  },
  {
    id: 'fl-03',
    category: 'floors_tiles',
    categoryNameSk: 'Obklady a podlahy',
    categoryNameRu: 'Плитка и напольные покрытия',
    nameSk: 'Kamenársky roh / zrezávanie hrán na 45° (jolly)',
    nameRu: 'Запил углов плитки под 45 градусов (заусовка)',
    unit: 'bm',
    defaultCostLabor: 10,
    defaultCostMaterial: 2,
    defaultClientPrice: 20,
  },
  {
    id: 'fl-04',
    category: 'floors_tiles',
    categoryNameSk: 'Obklady a podlahy',
    categoryNameRu: 'Плитка и напольные покрытия',
    nameSk: 'Hydroizolácia kúpeľne vrátane rohových pások (2 vrstvy)',
    nameRu: 'Гидроизоляция ванной (2 слоя + лента в углах)',
    unit: 'm2',
    defaultCostLabor: 4.5,
    defaultCostMaterial: 6.5,
    defaultClientPrice: 14,
  },
  {
    id: 'fl-05',
    category: 'floors_tiles',
    categoryNameSk: 'Obklady a podlahy',
    categoryNameRu: 'Плитка и напольные покрытия',
    nameSk: 'Pokládka laminátovej / vinylovej podlahy (click)',
    nameRu: 'Укладка ламината / винилового покрытия (клик)',
    unit: 'm2',
    defaultCostLabor: 4,
    defaultCostMaterial: 2,
    defaultClientPrice: 9.5,
  },

  // САНТЕХНИКА (Vodoinštalácia a kúrenie)
  {
    id: 'pl-01',
    category: 'plumbing',
    categoryNameSk: 'Vodoinštalácie',
    categoryNameRu: 'Сантехника и отопление',
    nameSk: 'Kompletná výmena rozvodov vody a odpadu (1 vývod)',
    nameRu: 'Разводка точки воды и канализации (1 точка)',
    unit: 'ks',
    defaultCostLabor: 45,
    defaultCostMaterial: 25,
    defaultClientPrice: 95,
  },
  {
    id: 'pl-02',
    category: 'plumbing',
    categoryNameSk: 'Vodoinštalácie',
    categoryNameRu: 'Сантехника и отопление',
    nameSk: 'Montáž podomietkového modulu Geberit',
    nameRu: 'Монтаж инсталляции подвесного унитаза (Geberit)',
    unit: 'ks',
    defaultCostLabor: 35,
    defaultCostMaterial: 15,
    defaultClientPrice: 75,
  },
  {
    id: 'pl-03',
    category: 'plumbing',
    categoryNameSk: 'Vodoinštalácie',
    categoryNameRu: 'Сантехника и отопление',
    nameSk: 'Montáž a zapojenie batérie, umývadla a sifónu',
    nameRu: 'Монтаж раковины, смесителя и сифона',
    unit: 'ks',
    defaultCostLabor: 25,
    defaultCostMaterial: 5,
    defaultClientPrice: 50,
  },
  {
    id: 'pl-04',
    category: 'plumbing',
    categoryNameSk: 'Vodoinštalácie',
    categoryNameRu: 'Сантехника и отопление',
    nameSk: 'Montáž sprchového kúta / sklenenej zásteny',
    nameRu: 'Монтаж душевой кабины / стеклянной перегородки',
    unit: 'ks',
    defaultCostLabor: 50,
    defaultCostMaterial: 10,
    defaultClientPrice: 110,
  },

  // ЭЛЕКТРИКА (Elektroinštalácia)
  {
    id: 'el-01',
    category: 'electrical',
    categoryNameSk: 'Elektroinštalácie',
    categoryNameRu: 'Электромонтажные работы',
    nameSk: 'Elektroinštalačný bod (drážkovanie, kábel, krabička)',
    nameRu: 'Точка электрики (штроба, кабель, подрозетник)',
    unit: 'ks',
    defaultCostLabor: 12,
    defaultCostMaterial: 6,
    defaultClientPrice: 25,
  },
  {
    id: 'el-02',
    category: 'electrical',
    categoryNameSk: 'Elektroinštalácie',
    categoryNameRu: 'Электромонтажные работы',
    nameSk: 'Kompletné zapojenie rozvádzača (ističe, prúdový chránič)',
    nameRu: 'Сборка и расключение электрощита',
    unit: 'ks',
    defaultCostLabor: 120,
    defaultCostMaterial: 40,
    defaultClientPrice: 260,
  },
  {
    id: 'el-03',
    category: 'electrical',
    categoryNameSk: 'Elektroinštalácie',
    categoryNameRu: 'Электромонтажные работы',
    nameSk: 'Osadenie zásuvky / vypínača / svietidla',
    nameRu: 'Установка розетки / выключателя / светильника',
    unit: 'ks',
    defaultCostLabor: 3.5,
    defaultCostMaterial: 0.5,
    defaultClientPrice: 7.5,
  },

  // МАЛЯРНЫЕ РАБОТЫ (Maliarske a stierkarske práce)
  {
    id: 'pnt-01',
    category: 'painting',
    categoryNameSk: 'Maliarske práce',
    categoryNameRu: 'Малярные работы и шпаклевка',
    nameSk: 'Penetrácia podkladu (steny a stropy)',
    nameRu: 'Грунтовка стен и потолков глубокого проникновения',
    unit: 'm2',
    defaultCostLabor: 0.8,
    defaultCostMaterial: 0.4,
    defaultClientPrice: 1.8,
  },
  {
    id: 'pnt-02',
    category: 'painting',
    categoryNameSk: 'Maliarske práce',
    categoryNameRu: 'Малярные работы и шпаклевка',
    nameSk: 'Vysprávky a stierkovanie stien (2 vrstvy + brúsenie)',
    nameRu: 'Шпаклевка стен под покраску/обои (2 слоя + шлифовка)',
    unit: 'm2',
    defaultCostLabor: 4.5,
    defaultCostMaterial: 2.2,
    defaultClientPrice: 9.5,
  },
  {
    id: 'pnt-03',
    category: 'painting',
    categoryNameSk: 'Maliarske práce',
    categoryNameRu: 'Малярные работы и шпаклевка',
    nameSk: 'Maľovanie stien a stropov (biela farba, 2 vrstvy)',
    nameRu: 'Покраска стен и потолков (белая, 2 слоя)',
    unit: 'm2',
    defaultCostLabor: 2,
    defaultCostMaterial: 1.2,
    defaultClientPrice: 4.8,
  },
  {
    id: 'pnt-04',
    category: 'painting',
    categoryNameSk: 'Maliarske práce',
    categoryNameRu: 'Малярные работы и шпаклевка',
    nameSk: 'Maľovanie farebné / prémiové umývateľné farby (2 vrstvy)',
    nameRu: 'Покраска стен цветная / моющаяся (2 слоя)',
    unit: 'm2',
    defaultCostLabor: 2.5,
    defaultCostMaterial: 2.0,
    defaultClientPrice: 6.2,
  },
];
